version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./views/android
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
    volumes:
      - ./views/android:/app
    environment:
      NODE_ENV: development
